// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKMIvencDi85fANUSihZuBophyqvwtQvo',
    appId: '1:917979251021:web:1ff654fd9da92df23df704',
    messagingSenderId: '917979251021',
    projectId: 'mental-key-v2',
    authDomain: 'mental-key-v2.firebaseapp.com',
    storageBucket: 'mental-key-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyoVtoxBdZ1v97cauyoskvWvtx9LUYq0',
    appId: '1:917979251021:android:ff37fa9e12b5f4b43df704',
    messagingSenderId: '917979251021',
    projectId: 'mental-key-v2',
    storageBucket: 'mental-key-v2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKMIvencDi85fANUSihZuBophyqvwtQvo',
    appId: '1:917979251021:web:0d24611d0b10545f3df704',
    messagingSenderId: '917979251021',
    projectId: 'mental-key-v2',
    authDomain: 'mental-key-v2.firebaseapp.com',
    storageBucket: 'mental-key-v2.firebasestorage.app',
  );
}
