import '../models/department_localization_profile.dart';

class DepartmentLocalizationMap {
  const DepartmentLocalizationMap._();

  static const List<DepartmentLocalizationProfile> departments =
      <DepartmentLocalizationProfile>[
    DepartmentLocalizationProfile(
      departmentId: 'residential',
      nameAr: 'المساحة السكنية',
      nameEn: 'Residential',
      shortLabelAr: 'سكني',
      shortLabelEn: 'Residential',
      easyReadingAr: 'مساحة الناس واحتياجاتهم.',
      easyReadingEn: 'People and needs area.',
      screenReaderAr: 'قسم المساحة السكنية',
      screenReaderEn: 'Residential department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'commercial',
      nameAr: 'الاستخبارات التجارية',
      nameEn: 'Commercial',
      shortLabelAr: 'تجاري',
      shortLabelEn: 'Commercial',
      easyReadingAr: 'مساحة الطلب والعرض والفرص.',
      easyReadingEn: 'Demand, supply, and opportunity area.',
      screenReaderAr: 'قسم الاستخبارات التجارية',
      screenReaderEn: 'Commercial intelligence department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'technical',
      nameAr: 'القسم التقني',
      nameEn: 'Technical',
      shortLabelAr: 'تقني',
      shortLabelEn: 'Technical',
      easyReadingAr: 'مساحة الأعطال والإصلاحات التقنية.',
      easyReadingEn: 'Technical issues and fixes area.',
      screenReaderAr: 'القسم التقني',
      screenReaderEn: 'Technical department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'support',
      nameAr: 'قسم الدعم',
      nameEn: 'Support',
      shortLabelAr: 'دعم',
      shortLabelEn: 'Support',
      easyReadingAr: 'مساحة المساعدة والتواصل.',
      easyReadingEn: 'Help and contact area.',
      screenReaderAr: 'قسم الدعم',
      screenReaderEn: 'Support department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'registry',
      nameAr: 'قسم السجل',
      nameEn: 'Registry',
      shortLabelAr: 'سجل',
      shortLabelEn: 'Registry',
      easyReadingAr: 'مساحة تنظيم الأدوات والموارد.',
      easyReadingEn: 'Tools and resources organization area.',
      screenReaderAr: 'قسم السجل',
      screenReaderEn: 'Registry department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'declaration_review',
      nameAr: 'مراجعة الإعلانات',
      nameEn: 'Declaration Review',
      shortLabelAr: 'مراجعة',
      shortLabelEn: 'Review',
      easyReadingAr: 'مساحة التأكد من اكتمال البيانات المعلنة.',
      easyReadingEn: 'Declared information completeness area.',
      screenReaderAr: 'قسم مراجعة الإعلانات',
      screenReaderEn: 'Declaration review department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'commercial_services',
      nameAr: 'الخدمات التجارية',
      nameEn: 'Commercial Services',
      shortLabelAr: 'خدمات',
      shortLabelEn: 'Services',
      easyReadingAr: 'مساحة الخدمات المهنية والتجارية.',
      easyReadingEn: 'Professional and commercial services area.',
      screenReaderAr: 'قسم الخدمات التجارية',
      screenReaderEn: 'Commercial services department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'archive',
      nameAr: 'الأرشيف',
      nameEn: 'Archive',
      shortLabelAr: 'أرشيف',
      shortLabelEn: 'Archive',
      easyReadingAr: 'مساحة حفظ الذاكرة والتقارير.',
      easyReadingEn: 'Memory and reports preservation area.',
      screenReaderAr: 'قسم الأرشيف',
      screenReaderEn: 'Archive department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'monitoring',
      nameAr: 'المراقبة',
      nameEn: 'Monitoring',
      shortLabelAr: 'مراقبة',
      shortLabelEn: 'Monitoring',
      easyReadingAr: 'مساحة متابعة الاتجاهات والاحتياجات.',
      easyReadingEn: 'Trends and needs observation area.',
      screenReaderAr: 'قسم المراقبة',
      screenReaderEn: 'Monitoring department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'owner_strategy',
      nameAr: 'استراتيجية المالك',
      nameEn: 'Owner Strategy',
      shortLabelAr: 'استراتيجية',
      shortLabelEn: 'Strategy',
      easyReadingAr: 'مساحة الرؤية والحماية السيادية.',
      easyReadingEn: 'Vision and sovereign protection area.',
      screenReaderAr: 'قسم استراتيجية المالك',
      screenReaderEn: 'Owner strategy department',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'owner',
      nameAr: 'المالك السيادي',
      nameEn: 'Owner',
      shortLabelAr: 'مالك',
      shortLabelEn: 'Owner',
      easyReadingAr: 'مساحة الهوية والسيادة.',
      easyReadingEn: 'Identity and sovereignty area.',
      screenReaderAr: 'المالك السيادي',
      screenReaderEn: 'Sovereign owner',
    ),
    DepartmentLocalizationProfile(
      departmentId: 'ecosystem',
      nameAr: 'النظام البيئي',
      nameEn: 'Ecosystem',
      shortLabelAr: 'نظام',
      shortLabelEn: 'Ecosystem',
      easyReadingAr: 'مساحة الشركاء والموارد الخارجية.',
      easyReadingEn: 'Partners and external resources area.',
      screenReaderAr: 'قسم النظام البيئي',
      screenReaderEn: 'Ecosystem department',
    ),
  ];
}
